### ISSUE TITLE
ubuntu 관련 내용의 커스텀마이징이 있음

### ISSUE THREAD

**Issue by minwook-shin** [minwook-shin/q2a-korean-translation#1]
우분투 한국위키에 쓰인 번역본이라서 qa-lang-admin.php 파일에 
'block_words_note' => '모든 문자와 일치하도록 \* 를 사용합니다. 예시: 우분투 (오직 우분투만 인식될것) , 우분투\* (우분투설치 혹은 우분투오류도 인식됨) , *분투 (주분투,루분투등도 인식됨).'
이라고 써져있습니다.
당신이 원하는 예시를 써주십시오

**Comment by sebuls** [comment]
An example is different original. 이 문장을 우리말로 번역하면 무엇인가요? 이 문장의 뜻을 몰라서요.

**Comment by minwook-shin** [comment]
Deleted issues.
