### ISSUE TITLE
한국어 번역 README는 영어...

### ISSUE THREAD

**Issue by sebuls** [minwook-shin/q2a-korean-translation#14]
github 이 사이트가 국제적인 사이트이긴 한데... 한국어 번역의 ReadMe 파일을 영어로 쓰신 까닭이 궁금합니다. 한국어로 쓰시면 어떨까요? 번역에 참여하실 분이라면 ReadMe 파일 해석 정도야 하시겠지만...

영어 그딴 거 필요없고 번역본만 필요해 라고 하는 분들도 q2a 한국어 파일을 쓸 수 있도록 하시면 더 좋을 거 같아요.

**Comment by minwook-shin** [comment]
당연히 국제적인 사람들이 많은 깃허브니까 영어로 쓰는것이고,
또한 q2a는 개발진이 외국인이므로 영문으로 써야합니다.
그리하여 readme에 한국어를 넣으려면, 한글,영어 중복 표기를 해야되는데...
이렇게되면 더 많은 시간이 걸릴뿐더러
추후에 시간이 지나서 서로 정보가 달라지는 문제점이 있습니다.

번역본만 필요하신분을 위해 readme에
https://github.com/minwook-shin/q2a-korean-translation/archive/master.zip
링크를 추가했습니다.

**Comment by sebuls** [comment]
readme에서 Question2Answer korean translation 100% complete 무슨 뜻이죠? 제가 해석을 잘 못 하겠어요. q2a 한국어 번역 100퍼센트 완벽하다? 이리 번역하면 되나요? 100퍼선트 완벽이라는 게 현실적으로 쉽지 않은 얘기라서...  Question2Answer korean translation 100% complete 를 우리말로 설명해 주셔요.

**Comment by minwook-shin** [comment]
removed

**Comment by ghost** [comment]
여기를 보시면, https://ask.ubuntu-kr.org/?qa=70
세벌님이 댓글을 달아놓으신 것이 있습니다.
한국어 관련 프로젝트 진행자를 일부러 괴롭히는 행위를 삼가시기 바랍니다.

```
 댓글 2015 6월 10 세벌 님
100퍼센트 한국어 번역 고맙습니다.
공식 페이지에 제가 올린 글... 저도 잊고 있었는데 이렇게 공개하시니 부끄럽네요.
맞아요. 제가 봐도 번역률이 매우 낮았으니까요.
번역이 놀랍도록 부분만 있고... 는
번역이 믿기 힘들 정도로 부분적이고 라고 하시는게 좀 더 자연스러울 것 같아요.
번역이 정말 정말 정말 쉽지 않다는 걸 느낍니다.
고맙습니다.
```

**Comment by minwook-shin** [comment]
[세벌님의 개인 홈페이지의 글을 인용했습니다.](http://sebul.sarang.net/q2a/?qa=79/woensug-eric-choi-ko-korean-%EB%8B%98-%EC%95%84%EC%8B%9C%EB%82%98%EC%9A%94)

> 100% complete에 대해... 처음엔 저도 원문을 전부 번역했다는 뜻으로 알고 있었지요. 그런데 한참 후에 보니 100% 완벽하다로 해석할수 있겠더군요. complete를 사전에서 찾아보셔요. 원저자가 제 의견을 반영하여 https://github.com/minwook-shin/q2a-korean-translation 에서 100% complete 라는 표현을 빼셨네요.

맘대로 짐작하지마세요. 반영한것이 아닙니다. 
이 무의미한 이슈를 끝내고 싶어서 해당문구를 삭제했을 뿐입니다.
그렇게 생각하셨으면 제 판단미스였으니 복구하겠습니다.

**Comment by minwook-shin** [comment]
그리고 세벌님께선 먼저 작성하신 #13 이슈으로 보았을때 이미 "100%"에 대하여 이해하고 계시다는것을 알 수 있습니다.

> Question2Answer korean translation 100% complete
> 이제 번역할 게 없나요? 전체적으로 훌륭한데 번역이 이상한 부분이 가끔 눈에 띄네요.

(세벌님께서 불과 7일전에 작성하신 이슈입니다.)

...

차라리 100%라는 문구가 거슬리신다면 솔직하게 말씀해주세요.

**Comment by sebuls** [comment]
100% complete 를 처음엔 저도 번역률이란 걸로 이해하고 있었지요. 한참 후에 보니 100% 완벽하다고 해석할 수도 있겠더군요. 오해의 소지가 있던 부분을 없앴다가 도로 돌려 놓은 건 이해하기 어렵군요ㅠ

**Comment by minwook-shin** [comment]
이해하기 어렵다고하시니 다시 한번 더 말씀드립니다.

문구 삭제는 **세벌님의 무의미한 이슈를 끝내기위한 조치**였고,
그 후 세벌님의 개인사이트에서 마치 이 프로젝트에 기여한것처럼 "본인의 의견이 반영됬다"라고 **착각하셔서** 다시 복구했을뿐입니다.

**Comment by ghost** [comment]
> 100% complete 를 처음엔 저도 번역률이란 걸로 이해하고 있었지요. 한참 후에 보니 100% 완벽하다고 해석할 수도 있겠더군요. 오해의 소지가 있던 부분을 없앴다가 도로 돌려 놓은 건 이해하기 어렵군요ㅠ

Question2Answer korean translation 100% complete 라는 표현은 오해의 소지가 없는 표현입니다. 국제 사회에서 사람들이 100% 번역이 완료되었다고 이해합니다. 세벌님 혼자서 일부러 곡해하고 있는 것이죠.
만약 진정으로 그 의미를 모르신다면, 번역을 시도하지 마십시오. 이 곳은 영어를 가르쳐 드리는 곳이 아닙니다. 영어 공부는 영어 교육 기관에서 교육 받으시기 바랍니다.
앞으로 세벌님은 q2a-korean-translation 프로젝트 뿐만 아니라 한국어/한글 관련 프로젝트에 글을 작성하지 마십시오.
앞으로도 지속적으로 훼방 놓거나 업무를 방해하거나 음해를 시도하시면 법적 대응을 강구하도록 하겠습니다. 세벌님께 드리는 마지막 경고입니다.

**Comment by sebuls** [comment]
cogniti 님 보십시오.
minwook-shin 님 페이지에서 cogniti 님과 제가 다투는 묘한 모습이 되었네요.
댁이 저에게 번역을 하라 마라 할 권한이 있나요? 무슨 법적 근거가 있나요?
q2a-korean-translation 프로젝트 뿐만 아니라 한국어/한글 관련 프로젝트에 글을 작성하지 마십시오.
라고 하실 권한이 님에게 있는 건가요?
법적대응 하려면 하십시오. 제가 법을 잘 몰라서 겁은 나네요.
마지막 경고요? 이건 뭔가요? 협박인가요? 경고 하려면 저에게 메일로 하던지 제 홈페이지에서 하던지 하십시오.
minwook-shin 님 보십시오.
제 표현력이 부족하여 minwook-shin 님 기분상하게 한 것에 대해서는 죄송합니다.
cogniti님과 할 얘기를 minwook-shin 님 페이지에서 한 것도 죄송.

**Comment by minwook-shin** [comment]
> minwook-shin 님 보십시오.
> 제 표현력이 부족하여 minwook-shin 님 기분상하게 한 것에 대해서는 죄송합니다.
> cogniti님과 할 얘기를 minwook-shin 님 페이지에서 한 것도 죄송. - sebuls commented  -

표현력이 부족한것은 적어도 **글 올리기전에 다시 한번 검토해보는 습관**으로 고쳐집니다.
표현력을 탓하지말아주세요.

---

ps.
찾아보니 이 이슈와 매우 비슷한 이슈가 있더군요. 공유합니다.
https://github.com/dasom-im/dasom/issues/20

**Comment by sebuls** [comment]
차라리 100%라는 문구가 거슬리신다면 솔직하게 말씀해주세요. 라고 하셨군요.
답변 드리죠.
예. 거슬립니다. complete 라는 표현도 거슬립니다.

**Comment by minwook-shin** [comment]
locked
