### ISSUE TITLE
날짜 표기 형식

### ISSUE THREAD

**Issue by sebuls** [minwook-shin/q2a-korean-translation#16]
http://www.masterqna.com/android/questions?start=19980
을 보면 
정기야 (90 포인트) 님이 2013년 4월 21일 질문
이런 형식으로 나옵니다.

그런데
https://ask.ubuntu-kr.org/?qa=questions&start=120
을 보면
문의 2015 5월 17 데스크탑 / 노트북의 ghg 님
이런 식으로 나옵니다.(2015년 5월 17일 이라고 나타나지 않고 년, 일 글자 빠짐)

날짜형식을 yyyy년 m월 d일 형식으로 나타내려면 어떻게 하나요?

덧.
q2a를 한국어로 최초로 번역한 사람은 minwook-shin 님도 아니고 저도 아니고 다른 사람인가 봅니다. http://www.masterqna.com/android/ 가 2013년 이전에 시작한 걸 보면...

**Comment by minwook-shin** [comment]
https://github.com/minwook-shin/q2a-korean-translation/issues/18
