### ISSUE TITLE
관리자 페이지만 영문으로 나타나게 하려면?

### ISSUE THREAD

**Issue by sebuls** [minwook-shin/q2a-korean-translation#17]
일반 사용자가 보는 화면은 한국어 번역이 나타나고, 관리자 페이지로 들어가면 한국어 번역 대신 영어 원본 그대로 나타나게 하려면 어떻게 하나요?

**Comment by minwook-shin** [comment]
기술 지원은 제 담당이 아닙니다.

**Comment by sebuls** [comment]
제가 질문한 것에 대한 답을 찾았기에 공유합니다. qa-lang/ko/ 디렉토리에서 qa-lang-admin.php 와 qa-lang-options.php 이 두 개 파일을 지우면 되네요.
