### ISSUE TITLE
날짜 형식 오류

### ISSUE THREAD

**Issue by sebuls** [minwook-shin/q2a-korean-translation#18]
minwook-shin 님의 번역에 날짜 형식 오류 있습니다.
오류 내용 : 년 일 글짜 빠짐

참고 자료
http://www.masterqna.com/android/questions?start=19980 에는
크라피카 (180 포인트) 님이 2013년 4월 29일 질문
이런 형식으로 나옵니다.

https://ask.ubuntu-kr.org/?qa=questions&start=135 에는
문의 2015 5월 17 데스크탑 / 노트북의 ghg 님
이런 식으로 나옵니다.5월 17일 이라고 나타나지 않고 년, 일 글자 빠짐)

**Comment by minwook-shin** [comment]
> minwook-shin 님의 번역에 날짜 형식 오류 있습니다. - sebuls commented -

번역상의 오류가 아닙니다. 번역에서 오류란, 
**번역활동을 통해 링크가 깨지거나 기타기능에 손상을 입히는것**을 말합니다.
만약 오류가 나면 홈페이지에 등록되기전에 q2a 개발팀에서 메일이 옵니다.
실제로 저도 한번 메일 받아봤고, 지금 버전은 해당 구문이 수정 후 통과된것입니다.

ask.ubuntu-kr.org 는 q2a 공식 번역을 쓸 뿐이며, 그 외 관련은 없습니다.
그리고 저번에도 말씀드렸다시피 q2a의 기술지원은 저의 담당이 아닙니다.

> http://www.masterqna.com/android/questions?start=19980 에는
> 크라피카 (180 포인트) 님이 2013년 4월 29일 질문
> 이런 형식으로 나옵니다.
> https://ask.ubuntu-kr.org/?qa=questions&start=135 에는
> 문의 2015 5월 17 데스크탑 / 노트북의 ghg 님
> 이런 식으로 나옵니다.5월 17일 이라고 나타나지 않고 년, 일 글자 빠짐) - sebuls commented -

그리고... 타 사이트를 닉네임까지 긁어와서 비교하는것은 자제해주시기 바랍니다.
(https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28193)
(https://forum.ubuntu-kr.org/viewtopic.php?f=2&t=28322)

**Comment by sebuls** [comment]
번역 오류 맞습니다. q2a 공식 사이트에 님의 한국어 번역이 들어갔다고 해서 그곳에서 한국어 문법이 맞았는지 틀렸는지 100퍼센트 검증했다고 생각하시나요? 그곳 사람들 한국어 잘 모를텐데요. http://sebul.sarang.net/q2a/?qa=103 참고하셔요.

**Comment by minwook-shin** [comment]
다시 한번 말씀드립니다. 해당 이슈는 번역오류가 아닙니다.
번역오류는 번역을 진행하다가 스트링이 실수로 빠지거나 하이퍼링크가 깨지는것을 말합니다.
또한 번역오류는 외국 개발팀이 손수 살펴봐주시는게 아니고, 번역 검사해주는 스크립트가 돌아가면서
틀린 부분을 빨간색으로 체크해주는것을 알려주는겁니다. 문법과는 무관합니다.
그리고 저는 이전 답변에서 "100% 전부 검증했다"라고 말 한적이 없습니다.
왜곡하지 말아주시기바랍니다.

---

제가 유독 이 이슈에 예민하게 대응하는 이유를 다수의 제 3자에게도 말씀드려야될거같아서 추가합니다.

> https://ask.ubuntu-kr.org/?qa=304
> 이런 다른 점이 있군요. 어쩌면 설정방법이 있을지도... 아시는 분 알려주셔요...
> - sebuls commented, From https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28305 -

q2a 한국어 프로젝트에서도 분란이 생기는것을 막는 조치입니다.

**Comment by ghost** [comment]
세벌님께서 말씀하신 부분은 저도 인지하고 있던 부분인데... 그게 버그로 보기에 좀 애매한 점이 있습니다.
http://php.net/manual/kr/function.date.php 여기를 보시면 php date 함수 설명이 있습니다.
년, 월, 일을 표현하는데 여러가지 표현이 있습니다.
http://php.net/manual/kr/function.setlocale.php 여기를 보시면 로케일을 설정할 수 있는 php 함수가 있습니다.
따라서 제가 알고 싶은 건 question2answer 에 로케일 설정할 수 있는 옵션이 있느냐는 것입니다.
만약 question2answer에 로케일 설정하는 옵션이 있다면 그걸 사용하면 될 것 같고, question2answer에 그런 기능이 없다면

```
        'date_format_other_years' => '^year년 ^month ^day일',
        'date_format_this_year' => '^month ^day일',
```

이렇게 변경하는 것이 합리적일 것 같습니다.

**Comment by sebuls** [comment]
locale 설정 옵션이 있는지 없는지는 저도 알아봐야겠네요. (locale 발음은 로케일보다는 로캘에 더 가까운 거 같네요.)
minwook-shin 님의 한국어 번역이 q2a 공식 홈페이지에 들어간 게
'100% 전부 검증했다는 것을 뜻하는 건 아니다'는데 대해서는 minwook-shin님과 제 생각이 같습니다.

우리나라에서 날짜를 쓸 때 2015 5월 17 이런 식으로 년, 일 글자는 빼고 월 글자만 넣는 곳이 어디 있나요?

**Comment by ghost** [comment]
오픈소스 프로젝트는 기본적으로 검증하지 않고 보증하지 않습니다. 무검증 및 무보증입니다. No Warranty 입니다.
보증이나 검증을 원하시면 그에 대한 비용을 지불하시고 보증 계약을 체결하시기 바랍니다.

참고로 question2answer 소프트웨어도 100% 검증된 것이 아니고 리눅스, 우분투 등도 100% 검증된 것이 아닙니다.
세벌님이 유독 q2a 번역본에 대하여 100% 검증된 것이 아니다고 강조하는 이유가 의심스럽습니다.
다음 번에도 반복되면 프로젝트 폄하 행위 및 업무 방해 행위로 인식하겠습니다.
기본적인 예의를 지켜주십시오.

**Comment by ghost** [comment]
q2a-korean-translation 은 GPL v2 라이선스이며 보증 책임이 없습니다.
이는 GPL v2 라이선스를 채택한 모든 소프트웨어가 마찬가지로 보증 책임이 없습니다.

보증 계약 체결하라는 얘기를 해서 거부 반응을 하시는 분이 있을까봐서 GPL v2 번역본에서 일부 발췌를 하겠습니다.
http://korea.gnu.org/documents/copyleft/gpl.ko.html

> 보증의 결여 (제11조, 제12조)
> 
> 제 11 조. 본 허가서를 따르는 프로그램은 무상으로 양도되기 때문에 관련 법률이 허용하는 한도 내에서 어떠한 형태의 보증도 제공되지 않습니다. 프로그램의 저작권자와 배포자가 공동 또는 개별적으로 별도의 보증을 서면으로 제공할 때를 제외하면, 특정한 목적에 대한 프로그램의 적합성이나 상업성 여부에 대한 보증을 포함한 어떠한 형태의 보증도 명시적이나 묵시적으로 설정되지 않은 ``있는 그대로의'' 상태로 이 프로그램을 배포합니다. 프로그램과 프로그램의 실행에 따라 발생할 수 있는 모든 위험은 피양도자에게 인수되며 이에 따른 보수 및 복구를 위한 제반 경비 또한 피양도자가 모두 부담해야 합니다.
> 
> 제 12 조. 저작권자나 배포자가 프로그램의 손상 가능성을 사전에 알고 있었다 하더라도 발생된 손실이 관련 법규에 의해 보호되고 있거나 이에 대한 별도의 서면 보증이 설정된 경우가 아니라면, 저작권자나 프로그램을 원래의 상태 또는 개작한 상태로 제공한 배포자는 프로그램의 사용이나 비작동으로 인해 발생된 손실이나 프로그램 자체의 손실에 대해 책임지지 않습니다. 이러한 면책 조건은 사용자나 제3자가 프로그램을 조작함으로써 발생된 손실이나 다른 소프트웨어와 프로그램을 함께 동작시키는 것으로 인해서 발생된 데이터의 상실 및 부정확한 산출 결과에만 국한되는 것이 아닙니다. 발생된 손실의 일반성이나 특수성 뿐 아니라 원인의 우발성 및 필연성도 전혀 고려되지 않습니다.

**Comment by sebuls** [comment]
100% 검증된 것이 아니다
100% 전부 검증했다는 것을 뜻하는 건 아니다
미묘한 차이가 있지요. 오해는 없으시길.

**Comment by cogniti** [comment]
> 100% 검증된 것이 아니다
> 100% 전부 검증했다는 것을 뜻하는 건 아니다
> 미묘한 차이가 있지요. 오해는 없으시길.

전체 부정, 부분 부정의 중의성이 있는데 그건 주제와는 상관 없는 얘기이고,
여기가 자유게시판, 잡담 게시판 이런 데가 아닙니다.
github.com 에서 issue 가지고 장난치지 마세요.

**Comment by minwook-shin** [comment]
해당 이슈와 관련하여 yeon333님께서 패치를 보내주셨습니다. https://github.com/minwook-shin/q2a-korean-translation/pull/19

yeon333님은 어제부로 q2a 한국어 프로젝트의 기여자로 등록되었습니다.

**Comment by minwook-shin** [comment]
yeon333님께 진심으로 감사의 인사를 드리며,
해당 이슈는 잠급니다.
