### ISSUE TITLE
한국어 1.8 버전은?

### ISSUE THREAD

**Issue by sebuls** [minwook-shin/q2a-korean-translation#23]
q2a 버전 1.8 나온 지 며칠 안 되었는데 한국어 버전 나왔나 보네요.
질문 드립니다
버전 1.7과 버전 1.8 한국어 번역 차이를 보려면 어떻게 하나요?

**Comment by rosebuntu** [comment]
넌 뭐하는 새끼인지?
lshort는 번역 다 했나? 그것도 그렇고
왜 남들 번역하는거에 자꾸 숟가락 얹을라 그러는지?
왜그러는거냐? 진짜 존나 궁금해서.
