### ISSUE TITLE
README에서 1.8개의 파일???

### ISSUE THREAD

**Issue by sebuls** [minwook-shin/q2a-korean-translation#4]
1.8개의 파일....
일쩜팔개의 파일이 뭔가 했습니다.
1과 8 사이에 띄어쓰기를 해 주시면 좋을 것 같습니다.
1. 8개의 파일... 이런 식으로요...
아니 그것보다는
1.  php 언어 파일 8개를 내려 받으십시오.
이런 식으로 하는 게 더 자연스러워 보이지 않나요?

**Comment by minwook-shin** [comment]
수정했습니다.  
감사합니다!
