### ISSUE TITLE
공식 홈페이지에 한국어가 들어감.

### ISSUE THREAD

**Issue by sebuls** [minwook-shin/q2a-korean-translation#5]
축하드립니다.
http://www.question2answer.org/addons.php
한국어가 들어갔네요. :)

**Comment by ghost** [comment]
이런건 이슈가 아닌데... 여기에 글 쓰시면 곤란해요. 이메일 오거든요. 예의 좀 지켜주세요.

**Comment by sebuls** [comment]
앗. 죄송합니다. 자동으로 메일이 가는지 몰랐네요. 앞으로 주의하겠습니다. ;-)
